services:
  myinfo:
    build: ./myinfo-web
    ports:
      - "8000:80"

  myinfo-web02:
    image: nginx
    volumes:
      - ./CT519-Assign3/myinfo-web02/:/usr/share/nginx/html
    ports:
      - "80:80"